[project]
name = "fellowship-tracker"
version = "0.1.0"
description = "Fellowship Eternal Tracker"
requires-python = ">=3.14"
dependencies = [
    "requests",
    "urllib3",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "ruff>=0.16.7",
    "ty>=0.0.81",
]



[tool.ruff.lint]
ignore = ["BLE001", "TRY002", "E501"]
extend-select = ["UP", "E", "F"]
