@echo off
echo Setting up Fellowship Eternal Tracker...
if not exist "config.json" (
    echo Copying config.example.json to config.json...
    copy config.example.json config.json
)
echo Syncing dependencies...
uv sync
echo Starting server...
uv run server.py
pause
